apiVersion: apps/v1
kind: Pod
metadata:
  name: omero-autotagger-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-autotagger
  template:
    metadata:
      labels:
        app: omero-autotagger
    spec:
      containers:
      - name: omero-autotagger
        image: omero_tagger_container:test
        env:
        - name: OMERO_SERVER
          value: 
        - name: OMERO_PORT
          value: 
        - name: OMERO_USER
          value:
        - name: OMERO_PASS
          value: 

        #envfrom: #secret
        ports:
        - containerPort: 8080
