apiVersion: batch/v1
kind: CronJob
metadata:
  name: omero-autotagger-cronjob
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: autotagger
            image: 
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: 
            - python3 /src/omero_autotagger/__main__.py /config/tag_rules.yml'
            - --patch /config/patch.py
            - -s ${OMERO_SERVER}
            - -p ${OMERO_PORT:-4064} 
            - -u ${OMERO_USER}
            - -w ${OMERO_PASS}
            - $([ ! -z $OMERO_SECURE ] && echo '-S')

            envFrom:
            - secretRef: 
              name: omero-connection-secret
            volumeMounts:
            - name: config-volume
              mountPath: /config

          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: omero-autotagger-config